language: rust

before_install:
  # install a newer cmake since at this time Travis only has version 2.8.7 and glfw-sys needs 2.8.12+
  - yes | sudo add-apt-repository ppa:kubuntu-ppa/backports
  - sudo apt-get update -qq

install: sudo apt-get install libXxf86vm-dev cmake
